### ISSUE TITLE
FIBO's Pull Request template should better reflect its process

### ISSUE THREAD

**Issue by rivettp** [edmcouncil/fibo#836]
It should ask people to confirm that:
- changes have been reconciled with latest master and no merge conflicts remain
- the PR is related to (exactly one) Issue and name it using a GitHub keyword such as closes
- Hygiene tests have been applied (by a PR with (WIP) in title
- the issue has been tested locally using a reasoner (for ontology changes)

**Comment by trypuz** [comment]
@rivettp, I agree with your proposal.

**Comment by trypuz** [comment]
No more comments here. I'll create PR including @rivettp's suggestions.

**Comment by trypuz** [comment]
@rivettp, one question, why do you want to require PR to be related to exactly one issue? I can imagine that we have a few issues indicating e.g. typos in the definitions. Wouldn't it make more sense to address the issues in one PR?

**Comment by rivettp** [comment]
@trypuz this has been a long-standing policy that has served us well and has a number of justifications, which include:

- when looking at a diff (either at time of a PR or at any time in future e.g. if doing a subsequent _blame_  in GitHub) it's clear WHY that code has changed.
- mingling changes from multiple issues makes it very hard to back one out if the approach to addressing that issue is not rejected, or even that the issue is not one that should be addressed at all (we may decide on WON'T FIX)
- makes it hard to review or discuss proposed changes if it's not clear which of many issues a changed line of code is meant to address and whether it does address the issue or is justified
_note: for this reason it's also important that a PR completely fix the single issue_
 - makes it harder to name pull requests or branches
- makes it a lot harder to synch with OMG's issue/change process which has voting and diffs per issue

If there are several similar typos they can all be consolidated into one issue if necessary.

**Comment by rivettp** [comment]
Reassigning to you @trypuz based on your comment that you would create the PR.

**Comment by trypuz** [comment]
Thanks! In fact, I'm still not convinced that we should require that "the PR is related to (exactly one) Issue".

**Comment by rivettp** [comment]
@trypuz imagine that a PR claims to fix 3 different issues, but on review it turns out that it does not actually fix one of them, or it has addressed it in an unacceptable way (e.g. that is against our ontology guidelines). What do we do then? Do we hold up the other 2 fixes that are OK?
That's in addition to the problems I mentioned earlier - for example, when reviewing the code diffs how do I know which change is meant to address which issue and hence whether the change is justified.
What argument do you have **for** multiple issues in one PR? A PR is not exactly hard work.

**Comment by trypuz** [comment]
PR template content proposal:

## Description



Fixes: #ISSUE_NUMBER

## Checklist:

- [ ] I'm familiar with the [FIBO developer quide](../CONTRIBUTING.md#contributing-to-the-fibo-code). My contribution meets all the requirements described there.
- [ ] My contribution follows the [principles of best practices for FIBO](../ONTOLOGY_GUIDE.md).
- [ ] My changes have been reconciled with the latest master and no merge conflicts remain.
- [ ] This PR is related to exactly one issue. The issue is referenced by using a GitHub keyword such as "fixes", "closes", or "resolves".
- [ ] Hygiene tests have been applied by a PR with "(WIP)" in the title.
- [ ] The issue has been tested locally using a reasoner (for ontology changes).

**Comment by rivettp** [comment]
Looks good, except for Hygiene tests we should add that there are no Errors remaining (Warnings are OK)

**Comment by trypuz** [comment]
> Looks good, except for Hygiene tests we should add that there are no Errors remaining (Warnings are OK)

IMO we should not add this. Before creating your PR, you cannot know if the hygiene test will pass or fail. If there are no errors, we will remove "WIP" from PR's title.
